# Formula transformation pipeline
# Each transform is applied in order to goreleaser-generated formulas

transforms:
  - name: hoist_methods
    config:
      # Methods to hoist from nested on_* blocks to class level
      methods:
        - install
        - test
        - caveats

  - name: reorder_methods
    config:
      # Reorder class-level methods/blocks (def install, test do, etc.) to this order
      methods:
        - install
        - test
        - caveats
